apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-cp-foundational-services-ibm-common-services
spec:
  destination:
    namespace: gitops-cp-foundational-services
    server: https://kubernetes.default.svc
  project: 2-services
  source:
    path: >-
      payload/2-services/namespace/gitops-cp-foundational-services/ibm-common-services
    repoURL: >-
      https://github.com/cloud-native-toolkit-test/gitops-cp-foundational-services
    targetRevision: main
    helm:
      releaseName: ibm-common-services
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
