apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespace-gitops-cp-foundational-services
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: 1-infrastructure
  source:
    path: >-
      payload/1-infrastructure/namespace/gitops-cp-foundational-services/namespace
    repoURL: >-
      https://github.com/cloud-native-toolkit-test/gitops-cp-foundational-services
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
